-- joined_orders_customers.sql
-- Generated by Baton (https://github.com/EndPx/baton) — grounded in DataHub metadata.
-- Goal: generate a dbt model joining orders and customers
-- Sources: orders, customers
-- Validated against the live DataHub schema (sqlglot, dialect=snowflake).

WITH orders AS ({{ ref('orders') }}), customers AS ({{ ref('customers') }}) SELECT orders.order_id, orders.order_date, orders.order_total, orders.customer_id, customers.cust_first_name, customers.cust_last_name, customers.cust_email FROM orders INNER JOIN customers ON orders.customer_id = customers.customer_id
