-- recent_orders_with_customers.sql
-- Generated by Baton (https://github.com/EndPx/baton) — grounded in DataHub metadata.
-- Goal: generate a dbt model joining orders and customers, filtered to the last 90 days
-- Sources: customers, orders
-- Validated against the live DataHub schema (sqlglot, dialect=snowflake).

WITH recent_orders AS (
SELECT *
FROM {{ ref('orders') }}
WHERE order_date >= DATEADD(day, -90, CURRENT_DATE) )
SELECT T1.order_id, T1.order_date, T1.order_total, T2.cust_first_name, T2.cust_last_name, T2.address_line1, T2.address_line2, T2.address_line3, T2.town_city, T2.zipcode
FROM recent_orders T1
INNER JOIN {{ ref('customers') }} T2 ON T1.customer_id = T2.customer_id
