/**
 * Publisher lane — packages the validated SQL into PR-ready dbt files and
 * closes the loop with DataHub by writing provenance back to the graph.
 *
 * Nodes: package_output → write_back (optional)
 * Produces the final PublishResult surfaced to the user.
 */

import { callTool } from "@/lib/mcp";
import type {
  CodegenResult,
  GeneratedFile,
  PublishResult,
  TraceEmitter,
} from "@/lib/baton";

const BATON_TAG = "generated-by-baton";

function buildSqlFile(result: CodegenResult): GeneratedFile {
  const header = `-- ${result.modelName}.sql
-- Generated by Baton (https://github.com/EndPx/baton) — grounded in DataHub metadata.
-- Goal: ${result.context.goal}
-- Sources: ${result.context.entities.map((e) => e.name).join(", ")}
-- Validated against the live DataHub schema (sqlglot, dialect=${result.context.dialect}).

`;
  return {
    name: `${result.modelName}.sql`,
    content: header + result.sql.trim() + "\n",
  };
}

function buildYmlFile(result: CodegenResult): GeneratedFile {
  const columns = result.validation.columnsUsed
    .map((c) => {
      // '"O"."ORDER_ID"' -> order_id
      const bare = c.split(".").pop()?.replace(/"/g, "").toLowerCase() ?? c;
      return bare;
    })
    .filter((v, i, arr) => arr.indexOf(v) === i);

  const columnYaml = columns
    .map((c) => `      - name: ${c}`)
    .join("\n");

  return {
    name: `${result.modelName}.yml`,
    content: `version: 2

models:
  - name: ${result.modelName}
    description: >
      ${result.notes.replace(/\n/g, " ")}
    columns:
${columnYaml}
`,
  };
}

export async function runPublisherLane(
  result: CodegenResult,
  emit: TraceEmitter,
  writeBackEnabled: boolean,
): Promise<PublishResult> {
  // --- Node: package_output ---
  emit({
    lane: "publisher",
    node: "package_output",
    type: "node_start",
    label: "Packaging PR-ready dbt model files",
  });

  const files = [buildSqlFile(result), buildYmlFile(result)];

  emit({
    lane: "publisher",
    node: "package_output",
    type: "node_complete",
    label: `Packaged ${files.map((f) => f.name).join(" + ")}`,
    data: { files: files.map((f) => f.name) },
  });

  // --- Node: write_back ---
  const taggedUrns: string[] = [];
  const errors: string[] = [];

  if (writeBackEnabled) {
    emit({
      lane: "publisher",
      node: "write_back",
      type: "node_start",
      label: "Writing provenance back to the DataHub graph",
    });

    const urns = result.context.entities.map((e) => e.urn);

    emit({
      lane: "publisher",
      node: "write_back",
      type: "tool_call",
      label: `MCP add_tags("${BATON_TAG}") on ${urns.length} source dataset(s)`,
      data: { tool: "add_tags", urns, tag: BATON_TAG },
    });

    for (const urn of urns) {
      try {
        const res = await callTool("add_tags", {
          urns: [urn],
          tag_name: BATON_TAG,
        });
        if (res.isError) {
          errors.push(`add_tags failed for ${urn}: ${res.raw.slice(0, 120)}`);
        } else {
          taggedUrns.push(urn);
        }
      } catch (err) {
        errors.push(
          `add_tags failed for ${urn}: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }

    emit({
      lane: "publisher",
      node: "write_back",
      type: "tool_result",
      label:
        errors.length === 0
          ? `Tagged ${taggedUrns.length} dataset(s) with "${BATON_TAG}" — the graph now records this generation`
          : `Tagged ${taggedUrns.length}, ${errors.length} failure(s)`,
      data: { taggedUrns, errors },
    });
    emit({
      lane: "publisher",
      node: "write_back",
      type: "node_complete",
      label: "Write-back done",
    });
  } else {
    emit({
      lane: "publisher",
      node: "write_back",
      type: "node_complete",
      label: "Write-back skipped (toggle off)",
    });
  }

  emit({
    lane: "publisher",
    node: "handoff",
    type: "pipeline_complete",
    label: `Done: ${files.length} files ready${taggedUrns.length ? `, ${taggedUrns.length} datasets tagged` : ""}`,
  });

  return {
    files,
    writeBack: { enabled: writeBackEnabled, taggedUrns, errors },
  };
}
